# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: a2
instance_flavor: uom.mse.2c9g


# Volume
volumes:
  - vol_name: vol-1
    vol_size: 60
  - vol_name: vol-2
    vol_size: 60
  - vol_name: vol-3
    vol_size: 60


#Security groups
security_groups:
  - name: ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: http-1
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: http-2
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb
    description: "couchdb 5984"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: cluster_communication1
    description: "couchdb 9100 - 9200"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

  - name: cluster_communication2
    description: "couchdb 4369"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0


# Instances
instances:
  - name: instance-1
    volumes: ['vol-1']
  - name: instance-2
    volumes: ['vol-2']
  - name: instance-3
    volumes: ['vol-3']

    
