---
# Uninstall old Docker
- name: Uninstall old versions of docker
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

# Install Docker dependencies
- name: Install dependencies
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes
  # environment: "{{ proxy_env }}"

# Add Docker repository key
- name: Add Docker apt repository key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  # environment: "{{ proxy_env }}"

# Add Docker repository
- name: Add Docker apt repository and update apt cache
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present
  # environment: "{{proxy_env}}"

# Install Docker
- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes
  # environment: "{{proxy_env}}"
  

# Install Docker compose
- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest
  # environment: "{{proxy_env}}"




# Restarting Daemon and docker service
- name: Daemon and service Reload
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker.service
