# Add nodes to CouchDB cluster
- name: Add nodes to CouchDB cluster
  become: yes
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    return_content: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ user }}\", \"password\": \"{{ pass }}\", \"port\": \"5984\", \"remote_node\": \"{{ inventory_hostname }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ user }}\", \"remote_current_password\":\"{{ pass }}\"}"

# Join nodes to CouchDB cluster
- name: Join nodes to CouchDB cluster
  become: yes
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201, 409
    return_content: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ inventory_hostname}}\",\"port\":\"5984\",\"username\":\"{{ user }}\",\"password\":\"{{ pass }}\"}"

# Empty request to avoid error messages when finishing cluster setup
- name: Empty request to avoid error messages when finishing cluster setup
  become: yes
  uri:
    url: http://{{ masternode }}:5984/
    method: GET
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
  run_once: true

# Finish cluster setup
- name: Finish cluster setup
  become: yes
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 201, 400
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"
  run_once: true
